// EzzDigi Ezzgame Cloudflare Worker API
const CORS={"Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type","Access-Control-Max-Age":"86400"};
function json(data,status=200,req){const h={"Content-Type":"application/json; charset=utf-8",...CORS};const o=req?.headers.get("Origin");if(o)h["Access-Control-Allow-Origin"]=o;return new Response(JSON.stringify(data),{status,headers:h})}
const enc=s=>new TextEncoder().encode(s);
async function hmac(k,d){const key=await crypto.subtle.importKey("raw",k,{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",key,d))}
function hex(b){return [...b].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function validate(initData,token,maxAge=86400){if(!initData||!token)return null;const p=new URLSearchParams(initData),received=p.get("hash");if(!received)return null;p.delete("hash");const ad=Number(p.get("auth_date")||0);if(!ad||Math.floor(Date.now()/1000)-ad>maxAge)return null;const check=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join("\n");const secret=await hmac(enc("WebAppData"),enc(token));const calc=hex(await hmac(secret,enc(check)));if(calc.length!==received.length)return null;let diff=0;for(let i=0;i<calc.length;i++)diff|=calc.charCodeAt(i)^received.charCodeAt(i);if(diff)return null;try{const u=JSON.parse(p.get("user")||"null");return u?.id?u:null}catch{return null}}
async function member(env,id){const r=await fetch(`https://api.telegram.org/bot${env.BOT_TOKEN}/getChatMember?chat_id=${encodeURIComponent(env.CHANNEL_USERNAME)}&user_id=${encodeURIComponent(id)}`);const d=await r.json();if(!r.ok||!d.ok)throw new Error(d?.description||"Telegram API error");return ["creator","administrator","member"].includes(d.result?.status)}
async function schema(env){if(!env.DB)return;await env.DB.prepare(`CREATE TABLE IF NOT EXISTS scores (telegram_id TEXT PRIMARY KEY, username TEXT, name TEXT NOT NULL, level INTEGER NOT NULL DEFAULT 1, coins INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL)`).run();await env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_scores_coins ON scores(coins DESC)`).run()}
async function auth(req,env){let b={};try{b=await req.clone().json()}catch{}const u=await validate(b?.initData,env.BOT_TOKEN,Number(env.INITDATA_MAX_AGE_SECONDS||86400));if(!u)return{error:"invalid_init_data"};try{return{user:u,member:await member(env,u.id)}}catch{return{error:"telegram_api_error"}}}
async function check(req,env){const a=await auth(req,env);if(a.error==="invalid_init_data")return json({member:false,error:a.error},401,req);if(a.error)return json({member:false,error:"telegram_api_unavailable"},502,req);return json({member:a.member,userId:String(a.user.id),username:a.user.username||"",name:[a.user.first_name,a.user.last_name].filter(Boolean).join(" ")},200,req)}
async function sync(req,env){const a=await auth(req,env);if(a.error==="invalid_init_data")return json({ok:false,error:a.error},401,req);if(a.error)return json({ok:false,error:"telegram_api_unavailable"},502,req);if(!a.member)return json({ok:false,member:false,reset:true,coins:0,level:1},403,req);if(!env.DB)return json({ok:false,error:"d1_not_bound"},500,req);await schema(env);let b={};try{b=await req.clone().json()}catch{return json({ok:false,error:"invalid_json"},400,req)}const id=String(a.user.id),coins=Math.max(0,Math.floor(Number(b.coins)||0)),level=Math.max(1,Math.floor(Number(b.level)||1)),name=String(b.name||[a.user.first_name,a.user.last_name].filter(Boolean).join(" ")||"Player").slice(0,100),username=String(a.user.username||"").slice(0,100),now=Math.floor(Date.now()/1000);const old=await env.DB.prepare("SELECT coins,level FROM scores WHERE telegram_id=?").bind(id).first();const fc=Math.max(coins,Number(old?.coins||0)),fl=Math.max(level,Number(old?.level||1));await env.DB.prepare(`INSERT INTO scores(telegram_id,username,name,level,coins,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(telegram_id) DO UPDATE SET username=excluded.username,name=excluded.name,level=CASE WHEN excluded.level>scores.level THEN excluded.level ELSE scores.level END,coins=CASE WHEN excluded.coins>scores.coins THEN excluded.coins ELSE scores.coins END,updated_at=excluded.updated_at`).bind(id,username,name,fl,fc,now).run();const s=await env.DB.prepare("SELECT coins,level FROM scores WHERE telegram_id=?").bind(id).first();return json({ok:true,member:true,userId:id,coins:Number(s?.coins||0),level:Number(s?.level||1)},200,req)}
async function board(req,env){if(!env.DB)return json({ok:false,error:"d1_not_bound"},500,req);await schema(env);const u=new URL(req.url),user=await validate(u.searchParams.get("initData")||"",env.BOT_TOKEN,Number(env.INITDATA_MAX_AGE_SECONDS||86400));const top=await env.DB.prepare("SELECT telegram_id AS userId,username,name,level,coins FROM scores ORDER BY coins DESC,updated_at ASC LIMIT 20").all();let player=null;if(user?.id)player=await env.DB.prepare("SELECT telegram_id AS userId,username,name,level,coins,(SELECT COUNT(*)+1 FROM scores x WHERE x.coins>s.coins) AS rank FROM scores s WHERE telegram_id=?").bind(String(user.id)).first();const total=await env.DB.prepare("SELECT COUNT(*) AS total FROM scores").first();return json({ok:true,leaderboard:(top.results||[]).map((x,i)=>({...x,rank:i+1,coins:Number(x.coins||0),level:Number(x.level||1)})),player:player?{...player,rank:Number(player.rank||0),coins:Number(player.coins||0),level:Number(player.level||1)}:null,totalPlayers:Number(total?.total||0)},200,req)}
export default{async fetch(request,env){if(request.method==="OPTIONS"){const h={...CORS},o=request.headers.get("Origin");if(o)h["Access-Control-Allow-Origin"]=o;return new Response(null,{status:204,headers:h})}const path=new URL(request.url).pathname.replace(/\/+$/,"" )||"/";try{if(path==="/api/health"&&request.method==="GET"){let d1=false;if(env.DB){await schema(env);await env.DB.prepare("SELECT 1").first();d1=true}return json({ok:true,service:"EzzDigi Ezzgame API",d1,telegramConfigured:Boolean(env.BOT_TOKEN&&env.CHANNEL_USERNAME)},200,request)}if(path==="/api/check-membership"&&request.method==="POST")return check(request,env);if(path==="/api/score/sync"&&request.method==="POST")return sync(request,env);if(path==="/api/leaderboard"&&request.method==="GET")return board(request,env);if(env.ASSETS)return env.ASSETS.fetch(request);return json({ok:false,error:"not_found"},404,request)}catch(e){return json({ok:false,error:"server_error",message:String(e?.message||e)},500,request)}}};
